(package! verb)
(package! agent-shell)
(package! guess-language)
(package! mermaid-mode)
(package! mermaid-ts-mode)
(package! ob-mermaid)
(package! org-super-agenda)
(unless (string= "" (getenv "DOOM_CALDAV_SERVER"))
  (package! org-caldav))
(package! gptel :recipe (:nonrecursive t))
(package! mcp)
(package! catppuccin-theme)
(package! mpv)
(package! elfeed-tube-mpv)
(package! gptel-magit)
(package! gptel-agent)
(package! minuet)
(package! mcp-server
  :recipe (:type git :host github :repo "rhblind/emacs-mcp-server"
           :files ("*.el" "tools/*.el" "mcp-wrapper.py" "mcp-wrapper.sh")))
