(package! verb)
(package! copilot
  :recipe (:host github :repo "copilot-emacs/copilot.el" :files ("*.el")))
(package! eca
  :recipe (:host github :repo "editor-code-assistant/eca-emacs" :files ("*.el")))
(package! guess-language)
(package! mermaid-mode)
(package! mermaid-ts-mode)
(package! ob-mermaid)
(package! org-super-agenda)
(unless (string= "" (getenv "DOOM_CALDAV_SERVER"))
  (package! org-caldav))
(package! gptel :recipe (:nonrecursive t))
(package! mcp)
(package! catppuccin-theme)
(package! mpv)
(package! elfeed-tube-mpv)
(package! gptel-magit)
(package! gptel-agent)
(package! minuet)
